use-sort:
    group:
        - _main
        - Shopery
    group-type: each
    sort-type: alph
    sort-direction: asc

header: |
    /*
     * This file is part of the shopery\view package
     *
     * (c) Berny Cantos <be@rny.cc>
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     */
